# Generated by Django 3.0.9 on 2020-09-06 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobpost',
            name='status',
            field=models.IntegerField(choices=[(0, 'pending'), (1, 'Approve'), (2, 'Reject')], default=0, null=True),
        ),
    ]
