# Generated by Django 3.0.9 on 2020-08-19 15:57

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_auto_20200818_2303'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobpost',
            name='JobSpecification',
            field=ckeditor.fields.RichTextField(null=True, verbose_name='Job Specification'),
        ),
    ]
