# Generated by Django 3.0.9 on 2020-08-22 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0003_jobpost_jobspecification'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobpost',
            name='RequiredSkill',
        ),
        migrations.AddField(
            model_name='jobpost',
            name='RequiredSkill',
            field=models.CharField(max_length=250, null=True, verbose_name='Required Skills'),
        ),
    ]
