# Generated by Django 3.0.9 on 2020-08-22 07:08

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('jobs', '0004_auto_20200822_1201'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobpost',
            name='Save',
            field=models.ManyToManyField(blank=True, related_name='save', to=settings.AUTH_USER_MODEL),
        ),
    ]
