# Generated by Django 3.0.9 on 2020-09-09 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0004_auto_20200907_2053'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobpost',
            name='EndSalary',
            field=models.FloatField(blank=True, default=0.0, null=True, verbose_name='Salary End With'),
        ),
        migrations.AlterField(
            model_name='jobpost',
            name='SalaryStart',
            field=models.FloatField(blank=True, default=0.0, null=True, verbose_name='Salary Start With'),
        ),
    ]
