# Generated by Django 3.0.9 on 2020-08-22 07:45

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('jobs', '0005_jobpost_save'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobpost',
            name='Save',
        ),
        migrations.AddField(
            model_name='jobpost',
            name='SaveJob',
            field=models.ManyToManyField(blank=True, related_name='savejob', to=settings.AUTH_USER_MODEL),
        ),
    ]
