# Generated by Django 3.0.9 on 2020-08-23 14:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0007_jobapply'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobapply',
            name='jobpost',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jobpost', to='jobs.JobPost', verbose_name='Apply Job'),
        ),
    ]
