# Generated by Django 3.0.9 on 2020-08-23 16:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0008_auto_20200823_2034'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobapply',
            name='jobpost',
        ),
        migrations.AddField(
            model_name='jobapply',
            name='job',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='jobs.JobPost', verbose_name='Apply Job'),
            preserve_default=False,
        ),
    ]
