# Generated by Django 3.0.9 on 2020-08-25 08:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0009_auto_20200823_2244'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobapply',
            name='job',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jobapplys', to='jobs.JobPost', verbose_name='Apply Job'),
        ),
    ]
