# Generated by Django 3.0.9 on 2020-08-25 09:00

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0010_auto_20200825_1432'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='jobapply',
            options={'ordering': ['-ApplydDate']},
        ),
        migrations.AlterField(
            model_name='jobapply',
            name='ApplydDate',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Job Apply Date'),
        ),
    ]
