# Generated by Django 3.0.9 on 2020-08-25 12:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('jobs', '0011_auto_20200825_1445'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobapply',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applyersname', to=settings.AUTH_USER_MODEL),
        ),
    ]
