# Generated by Django 3.0.9 on 2020-08-08 15:16

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employerprofile',
            name='aboutCompany',
        ),
        migrations.AddField(
            model_name='employerprofile',
            name='AboutCompany',
            field=ckeditor.fields.RichTextField(null=True, verbose_name='About Company'),
        ),
        migrations.AddField(
            model_name='jobseekerprofile',
            name='WorkedField',
            field=models.CharField(max_length=50, null=True, verbose_name='Worked Related Fields'),
        ),
        migrations.AlterField(
            model_name='employerprofile',
            name='CompanyAddress',
            field=models.CharField(max_length=100, verbose_name='Company Address'),
        ),
        migrations.AlterField(
            model_name='employerprofile',
            name='CompanyCategory',
            field=models.ManyToManyField(to='account.Category', verbose_name='Company Category'),
        ),
        migrations.AlterField(
            model_name='employerprofile',
            name='CompanyEstablishDate',
            field=models.DateField(verbose_name='Company Established Date'),
        ),
        migrations.AlterField(
            model_name='employerprofile',
            name='CompanyLogo',
            field=models.ImageField(upload_to='Employer/Company_Logos', verbose_name='Company Logo'),
        ),
        migrations.AlterField(
            model_name='employerprofile',
            name='CompanyName',
            field=models.CharField(max_length=30, verbose_name='Company Name'),
        ),
        migrations.AlterField(
            model_name='employerprofile',
            name='CompanyOwnership',
            field=models.CharField(choices=[('PU', 'Public'), ('PV', 'Private'), ('GOV', 'Government'), ('O', 'Others')], max_length=3, verbose_name='Company Ownership'),
        ),
        migrations.AlterField(
            model_name='employerprofile',
            name='CompanyWebsite',
            field=models.URLField(max_length=100, verbose_name='Company Website'),
        ),
        migrations.AlterField(
            model_name='employerprofile',
            name='FirstName',
            field=models.CharField(max_length=30, verbose_name='First Name'),
        ),
        migrations.AlterField(
            model_name='employerprofile',
            name='LastName',
            field=models.CharField(max_length=30, verbose_name='Last Name'),
        ),
        migrations.AlterField(
            model_name='employerprofile',
            name='MobileNo',
            field=models.CharField(max_length=15, verbose_name='Mobile Number'),
        ),
        migrations.AlterField(
            model_name='employerprofile',
            name='PhoneNumber',
            field=models.CharField(max_length=20, verbose_name='Phone Number'),
        ),
        migrations.AlterField(
            model_name='employerprofile',
            name='TelNo',
            field=models.CharField(max_length=15, verbose_name='TelePhone Number'),
        ),
        migrations.AlterField(
            model_name='jobseekerprofile',
            name='AboutMe',
            field=ckeditor.fields.RichTextField(verbose_name='About Me'),
        ),
        migrations.AlterField(
            model_name='jobseekerprofile',
            name='CurrentAddress',
            field=models.CharField(max_length=100, verbose_name='Current Address'),
        ),
        migrations.AlterField(
            model_name='jobseekerprofile',
            name='DateOffBorth',
            field=models.DateField(verbose_name='Date Of Birth'),
        ),
        migrations.AlterField(
            model_name='jobseekerprofile',
            name='Education',
            field=models.CharField(choices=[('Intermidate Level Complete', 'Intermidate Level Complete'), ('Bacholer Running/Complete', 'Bacholer Running/Complete'), ('Master Running/Complete', 'Master Running/Complete'), ('Ph. D. Running/Complete', 'Ph. D. Running/Complete'), ('OTHER', 'OTHER')], max_length=26, verbose_name='Education'),
        ),
        migrations.AlterField(
            model_name='jobseekerprofile',
            name='EducationBoard',
            field=models.CharField(choices=[('NB', 'NEB'), ('TU', 'Tribhuvan Univercity'), ('MWU', 'Mid-Westran Univercity'), ('AFU', 'Architure and Forestry Univercity'), ('NOU', 'Nepal Open Univercity'), ('PU', 'Pokhara Univercity'), ('NSU', 'Nepal Sanskrit Univercity'), ('NBU', 'Lumbini Buddhist Univercity'), ('FWU', 'Far-Western Univercity'), ('KU', 'Kathmandu Univercity'), ('PU', 'Purbanchal Univercity'), ('O', 'Others')], max_length=3, verbose_name='Education Board'),
        ),
        migrations.AlterField(
            model_name='jobseekerprofile',
            name='EducationProgram',
            field=models.CharField(max_length=200, verbose_name='Education Program'),
        ),
        migrations.AlterField(
            model_name='jobseekerprofile',
            name='Email',
            field=models.EmailField(max_length=30, verbose_name='Email Address'),
        ),
        migrations.AlterField(
            model_name='jobseekerprofile',
            name='FirstName',
            field=models.CharField(max_length=30, verbose_name='First Name'),
        ),
        migrations.AlterField(
            model_name='jobseekerprofile',
            name='JobCategory',
            field=models.ManyToManyField(to='account.Category', verbose_name='Job Category'),
        ),
        migrations.AlterField(
            model_name='jobseekerprofile',
            name='LastName',
            field=models.CharField(max_length=30, verbose_name='Last Name'),
        ),
        migrations.AlterField(
            model_name='jobseekerprofile',
            name='MarrigeStatus',
            field=models.CharField(choices=[('single', 'Single'), ('married', 'Married')], max_length=7, verbose_name='Marrige Status'),
        ),
        migrations.AlterField(
            model_name='jobseekerprofile',
            name='MySkill',
            field=models.ManyToManyField(to='account.Skill', verbose_name='My Skill'),
        ),
        migrations.AlterField(
            model_name='jobseekerprofile',
            name='NameOfInstitute',
            field=models.CharField(max_length=200, verbose_name='Name Of Institute'),
        ),
        migrations.AlterField(
            model_name='jobseekerprofile',
            name='PernamentAddress',
            field=models.CharField(max_length=100, verbose_name='Pernament Address'),
        ),
        migrations.AlterField(
            model_name='jobseekerprofile',
            name='PhoneNumber',
            field=models.CharField(max_length=20, verbose_name='Phone Number'),
        ),
        migrations.AlterField(
            model_name='jobseekerprofile',
            name='ProfileImage',
            field=models.ImageField(upload_to='Jobseeker/Profile_Pictures', verbose_name='Profile Picture'),
        ),
        migrations.AlterField(
            model_name='jobseekerprofile',
            name='UploadCv',
            field=models.FileField(upload_to='Jobseeker/CVs', verbose_name='Upload Your CV'),
        ),
        migrations.AlterField(
            model_name='jobseekerprofile',
            name='WorkedCompanyName',
            field=models.CharField(max_length=200, verbose_name='Worked Company Name'),
        ),
        migrations.AlterField(
            model_name='jobseekerprofile',
            name='WorkedCompanyWebsite',
            field=models.URLField(verbose_name='Worked Company Website'),
        ),
        migrations.AlterField(
            model_name='jobseekerprofile',
            name='WorkingExperience',
            field=models.IntegerField(default=0, verbose_name='Working Experience'),
        ),
    ]
