# Generated by Django 3.0.9 on 2020-08-12 07:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobseekerprofile',
            name='ProfileImage',
        ),
        migrations.RemoveField(
            model_name='jobseekerprofile',
            name='UploadCv',
        ),
    ]
