# Generated by Django 3.0.9 on 2020-08-12 08:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_auto_20200812_1332'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobseekerprofile',
            name='DateOffBorth',
        ),
    ]
