# Generated by Django 3.0.9 on 2020-08-12 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_remove_jobseekerprofile_dateoffborth'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobseekerprofile',
            name='ProfileImage',
            field=models.ImageField(default='defaultusers.jpg', upload_to='Jobseeker/Profile_Pictures', verbose_name='Profile Picture'),
        ),
        migrations.AddField(
            model_name='jobseekerprofile',
            name='UploadCv',
            field=models.FileField(null=True, upload_to='Jobseeker/CVs', verbose_name='Upload Your CV'),
        ),
    ]
