# Generated by Django 3.0.9 on 2020-08-12 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_auto_20200812_1417'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobseekerprofile',
            name='ProfileImage',
            field=models.ImageField(default='defaultusers.png', upload_to='Jobseeker/Profile_Pictures', verbose_name='Profile Picture'),
        ),
    ]
