# Generated by Django 3.0.9 on 2020-08-12 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_auto_20200812_1422'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employerprofile',
            name='CompanyEstablishDate',
            field=models.DateField(blank=True, null=True, verbose_name='Company Established Date'),
        ),
    ]
